version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: foyer
    ports:
      - "3306:3306"
  app:
    build: .
    image: medslah/foyer-app
    ports:
      - "8080:8080"
    depends_on:
      - db

