version: '3.8'

services:
  spring:
    image: foyer-app:latest 
    ports:
      - "8080:8080"  
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/your_database_name
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root_password
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password  
      MYSQL_DATABASE: your_database_name  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql 

volumes:
  mysql_data:
